# coding: utf-8
from sqlalchemy import Column, Index, VARCHAR, text
from sqlalchemy.dialects.oracle.base import NUMBER
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class Xsjbxxb(Base):
    __tablename__ = 'xsjbxxb'
    __table_args__ = (
        Index('xsjbxxb_index', 'xh', 'xzb', 'dqszj'),
    )

    xh = Column(VARCHAR(20), primary_key=True)
    xm = Column(VARCHAR(50))
    xb = Column(VARCHAR(2))
    csrq = Column(VARCHAR(10))
    zzmm = Column(VARCHAR(50))
    mz = Column(VARCHAR(15))
    jg = Column(VARCHAR(40))
    lydq = Column(VARCHAR(50))
    xy = Column(VARCHAR(30))
    xi = Column(VARCHAR(30))
    zymc = Column(VARCHAR(40), index=True)
    xzb = Column(VARCHAR(50), index=True)
    xz = Column(NUMBER(1, 0, False))
    xxnx = Column(NUMBER(2, 0, False))
    xjzt = Column(VARCHAR(20), server_default=text("'有'"))
    dqszj = Column(NUMBER(4, 0, False), index=True)
    pyfx = Column(VARCHAR(20))
    zyfx = Column(VARCHAR(30), index=True)
    zylb = Column(VARCHAR(20))
    rxrq = Column(VARCHAR(10))
    byzx = Column(VARCHAR(50))
    ssh = Column(VARCHAR(50))
    dzyxdz = Column(VARCHAR(40))
    lxdh = Column(VARCHAR(100))
    zkzh = Column(VARCHAR(20))
    sfzh = Column(VARCHAR(20))
    gatm = Column(VARCHAR(10))
    jkzk = Column(VARCHAR(10))
    ywxw = Column(VARCHAR(2))
    bz = Column(VARCHAR(250))
    mm = Column(VARCHAR(128))
    bdh = Column(VARCHAR(12))
    yydj = Column(NUMBER(1, 0, False))
    kh = Column(VARCHAR(30))
    zssj = Column(VARCHAR(20))
    rxzf = Column(VARCHAR(8))
    sfyxxs = Column(VARCHAR(2))
    xslb = Column(VARCHAR(10))
    dj = Column(VARCHAR(50), server_default=text("'00000000000000000000000000000000000000000000000000'"))
    sfgspydy = Column(VARCHAR(2))
    lqmcjyh = Column(VARCHAR(20))
    xmpy = Column(VARCHAR(50))
    yhzh = Column(VARCHAR(100))
    jxbmc = Column(VARCHAR(200))
    rdsj = Column(VARCHAR(20))
    zydm = Column(VARCHAR(4))
    ljbym = Column(VARCHAR(20))
    sfly = Column(VARCHAR(100))
    sfkzc = Column(VARCHAR(2), server_default=text("'否'"))
    cc = Column(VARCHAR(20))
    yzbm = Column(VARCHAR(10))
    yycj = Column(VARCHAR(10))
    kx = Column(VARCHAR(10), server_default=text("'0'"))
    sfzx = Column(VARCHAR(4), server_default=text("'是'"))
    xszh = Column(VARCHAR(20))
    userid = Column(VARCHAR(40))
    kslb = Column(VARCHAR(20))
    sfzc = Column(VARCHAR(10), server_default=text("""\
'是'

"""))
    ydlb = Column(VARCHAR(100))
    zym = Column(VARCHAR(20))
    byrq = Column(VARCHAR(10))
    csd = Column(VARCHAR(200))
    ljb = Column(VARCHAR(50))
    ljbc = Column(VARCHAR(50))
    ljbh = Column(VARCHAR(50))
    dzzch = Column(VARCHAR(50))
    ksh = Column(VARCHAR(50))
    ccqj = Column(VARCHAR(50))
    dlmc = Column(VARCHAR(50))
    kstz = Column(VARCHAR(20))
    tc = Column(VARCHAR(100))
    rxfs = Column(VARCHAR(20))
    sfzds = Column(VARCHAR(2), server_default=text("'否'"))
    bxxs = Column(VARCHAR(10))
    bxlx = Column(VARCHAR(40))
    xxxs = Column(VARCHAR(10))
    zsjj = Column(VARCHAR(4))
    shbj = Column(VARCHAR(6))
    yshbj = Column(VARCHAR(6))
    zxwyyz = Column(VARCHAR(20))
    zxwyjbmc = Column(VARCHAR(10))
    sfbzlb = Column(VARCHAR(50), server_default=text("""\
'1'

"""))
    dlm = Column(VARCHAR(20), index=True)
    sfkpj = Column(VARCHAR(4), server_default=text("'是'"))
    jtszd = Column(VARCHAR(120))
    lys = Column(VARCHAR(20))
    sfqr = Column(VARCHAR(2))
    sflxs = Column(VARCHAR(10))
    telnumber = Column(VARCHAR(20))
    tellx = Column(VARCHAR(50))
    xsmm = Column(VARCHAR(128))
    sfqxy = Column(VARCHAR(4))
    byf = Column(VARCHAR(20))
    xscbj = Column(VARCHAR(50))
    sfpdg = Column(VARCHAR(4), server_default=text("'是'"))
    kl = Column(VARCHAR(20))
    yktid = Column(VARCHAR(50))
    lqpc = Column(VARCHAR(50))
    ksjc = Column(VARCHAR(100))
    ybyzy = Column(VARCHAR(50))
    lqzy = Column(VARCHAR(50))
    zslb = Column(VARCHAR(20))
    sfcglx = Column(VARCHAR(2))
    yzydm = Column(VARCHAR(6))
    yzymc = Column(VARCHAR(50))
    fdjs = Column(VARCHAR(20), index=True)
    lqh = Column(VARCHAR(50))
    dsxm1 = Column(VARCHAR(30))
    dsxm2 = Column(VARCHAR(30))
    bzrxm1 = Column(VARCHAR(30))
    bzrxm2 = Column(VARCHAR(30))
    ds1lxfs = Column(VARCHAR(250))
    ds2lxfs = Column(VARCHAR(250))
    bzr1lxfs = Column(VARCHAR(250))
    bzr2lxfs = Column(VARCHAR(250))
    hkszd = Column(VARCHAR(100))
    tdzy = Column(VARCHAR(10))
    sg = Column(VARCHAR(4))
    tz = Column(VARCHAR(4))
    qfqk = Column(VARCHAR(20))
    zzdd = Column(VARCHAR(250))
    ywrxrq = Column(VARCHAR(20))
    ywbyrq = Column(VARCHAR(20))
    ywcsrq = Column(VARCHAR(20))
    xy_xsxy = Column(VARCHAR(50))
    pyfs = Column(VARCHAR(30))
    zjlx = Column(VARCHAR(50))
    wpdw = Column(VARCHAR(50))
    wpdwdq = Column(VARCHAR(50))
    bysjzg = Column(VARCHAR(20))
    wpkh = Column(VARCHAR(50))
    xyd = Column(VARCHAR(30))
    dlmmm = Column(VARCHAR(128))
    whcd = Column(VARCHAR(8))
    rwsj = Column(VARCHAR(10))
    rwdq = Column(VARCHAR(20))
    ssjq = Column(VARCHAR(20))
    ydw = Column(VARCHAR(50))
    xjbh = Column(VARCHAR(15))
    rxpzsh = Column(VARCHAR(20))
    xylb = Column(VARCHAR(20))
    ejxk = Column(VARCHAR(20))
    ejxkssyy = Column(VARCHAR(20))
    jxpckzxx = Column(VARCHAR(4))
    xsxxxgyh = Column(VARCHAR(20))
    sfnz = Column(VARCHAR(2))
    hkxz = Column(VARCHAR(10))
    sfyb = Column(VARCHAR(2))
    sfsb = Column(VARCHAR(2))
    njkypckz = Column(VARCHAR(1))
    qfbs = Column(VARCHAR(2))
    ywxm = Column(VARCHAR(50))
    enstunum = Column(VARCHAR(20))
    zhfmynme = Column(VARCHAR(30))
    zhfstnme = Column(VARCHAR(30))
    sfbbxsz = Column(VARCHAR(2), server_default=text("""\
'否'

"""))
    bbxszsj = Column(VARCHAR(10))
    hcpyhzt = Column(VARCHAR(8), server_default=text("""\
'未购买'

"""))
    bz1 = Column(VARCHAR(250))
    bz2 = Column(VARCHAR(20))
    bz3 = Column(VARCHAR(240))
    lysfdm = Column(VARCHAR(10))
    lysdm = Column(VARCHAR(10))
    lyxdm = Column(VARCHAR(10))
    yhkh = Column(VARCHAR(25))
    xmpyxdqr = Column(VARCHAR(1))
    dj1 = Column(VARCHAR(20))
    mmsxsj = Column(VARCHAR(30), server_default=text("""\
to_char(sysdate,'YYYY-MM-DD HH24:MI:SS')
"""))
    sfkdc = Column(VARCHAR(2), server_default=text("""\
'是'
"""))
    gj = Column(VARCHAR(20))
    rxnj = Column(VARCHAR(10))
    sfhzc = Column(VARCHAR(2))
    hdxw = Column(VARCHAR(50))
    byjl = Column(VARCHAR(50))
    hzh = Column(VARCHAR(30))
    hzyxq = Column(VARCHAR(20))
    hzlx = Column(VARCHAR(30))
    qzyxq = Column(VARCHAR(20))
    sfyjb = Column(VARCHAR(20))
    jbqksm = Column(VARCHAR(200))
    zjxy = Column(VARCHAR(50))
    gzdw = Column(VARCHAR(100))
    jzxm = Column(VARCHAR(20))
    jzcw = Column(VARCHAR(20))
    jzdzyxdz = Column(VARCHAR(100))
    jzlxdh = Column(VARCHAR(100))
    sfcnr = Column(VARCHAR(2))
    zhswdbr = Column(VARCHAR(50))
    dbrdh = Column(VARCHAR(30))
    xxsj = Column(VARCHAR(20))
    sfgfs = Column(VARCHAR(2))
