# coding: utf-8
from sqlalchemy import Column, MetaData, Table, VARCHAR
from sqlalchemy.dialects.oracle.base import NUMBER

metadata = MetaData()

t_cjbmaxview = Table(
    'cjbmaxview', metadata,
    Column('xn', VARCHAR(10)),
    Column('xq', NUMBER(1, 0, False)),
    Column('xkkh', VARCHAR(50), nullable=False),
    Column('xh', VARCHAR(20), nullable=False),
    Column('xm', VARCHAR(50)),
    Column('kcmc', VARCHAR(110)),
    Column('qzxs', NUMBER(3, 1, True)),
    Column('xf', VARCHAR(5)),
    Column('cj', VARCHAR(8)),
    Column('zscj', NUMBER(5, 1, True)),
    Column('jd', NUMBER(asdecimal=False)),
    Column('bz', VARCHAR(250)),
    Column('xgsj', VARCHAR(200)),
    Column('xgs', VARCHAR(100)),
    Column('cxbj', NUMBER(1, 0, False)),
    Column('tzf', VARCHAR(20)),
    Column('tzfjd', NUMBER(3, 1, True)),
    Column('kcdm', VARCHAR(100)),
    Column('pscj', VARCHAR(20)),
    Column('qmcj', VARCHAR(20)),
    Column('sycj', VARCHAR(8)),
    Column('bkcj', VARCHAR(8)),
    Column('cxcj', VARCHAR(8)),
    Column('kcxz', VARCHAR(30)),
    Column('tj', NUMBER(1, 0, False)),
    Column('tjbz', NUMBER(1, 0, False)),
    Column('tzjd', NUMBER(3, 1, True)),
    Column('cxxnxq', VARCHAR(12)),
    Column('qzcj', VARCHAR(8)),
    Column('fxbj', VARCHAR(10)),
    Column('jf', NUMBER(asdecimal=False)),
    Column('kcgs', VARCHAR(20)),
    Column('xsqr', VARCHAR(4)),
    Column('zhxs', VARCHAR(20)),
    Column('bzxx', VARCHAR(150)),
    Column('dxqjl', VARCHAR(2)),
    Column('bkcj_tzf', VARCHAR(8)),
    Column('bkcj_bz', VARCHAR(10)),
    Column('llcj', VARCHAR(20)),
    Column('llzscj', VARCHAR(20)),
    Column('xmdm', VARCHAR(100)),
    Column('xmmc', VARCHAR(50)),
    Column('qmcj_bf', VARCHAR(20)),
    Column('gaxs', VARCHAR(20)),
    Column('jycj', VARCHAR(8)),
    Column('jybkcj', VARCHAR(8)),
    Column('fjf', VARCHAR(4)),
    Column('cjjf_bz', VARCHAR(100)),
    Column('cj1', VARCHAR(8)),
    Column('cj2', VARCHAR(8)),
    Column('cj3', VARCHAR(8)),
    Column('cj4', VARCHAR(8)),
    Column('cj5', VARCHAR(8)),
    Column('cj6', VARCHAR(8)),
    Column('cj7', VARCHAR(8)),
    Column('cj8', VARCHAR(8)),
    Column('cj9', VARCHAR(8)),
    Column('cj10', VARCHAR(8)),
    Column('zpn', VARCHAR(40)),
    Column('bkcjn', VARCHAR(40)),
    Column('cxcjn', VARCHAR(40)),
    Column('zpz', NUMBER(asdecimal=False)),
    Column('bkcjz', NUMBER(asdecimal=False)),
    Column('cxcjz', NUMBER(asdecimal=False)),
    Column('mcjn', NUMBER(asdecimal=False)),
    Column('mcjx', VARCHAR(10))
)
